# SPDX-FileCopyrightText: 2022 Agathe Porte <microjoe@microjoe.org>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[workspace]
members = [
    "gtk_liststore_item",
    "gtk_liststore_item_derive",
]
