# SPDX-FileCopyrightText: 2021 Agathe Porte <microjoe@microjoe.org>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

consolidate-commits = true
shared-version = true
consolidate-pushes = true
allow-branch = ["main"]

pre-release-commit-message = "chore: release {{version}}"
tag-message = "{{tag_name}}"
tag-name = "v{{version}}"
sign-tag = true
pre-release-replacements = [
  {file="README.md", search="gtk_liststore_item = .*", replace="gtk_liststore_item = \"{{version}}\""},
  {file="Cargo.toml", search="^version = \".*\"$", replace="version = \"{{version}}\""},
  {file="Cargo.toml", min=0, search="^gtk_liststore_item_derive = \\{ version = \".*\", path = \"../gtk_liststore_item_derive\" \\}$", replace="gtk_liststore_item_derive = { version = \"{{version}}\", path = \"../gtk_liststore_item_derive\" }"},
  {file="Cargo.toml", min=0, search="^gtk_liststore_item_derive = \\{ version = \".*\", optional = true, path = \"../gtk_liststore_item_derive\" \\}$", replace="gtk_liststore_item_derive = { version = \"{{version}}\", optional = true, path = \"../gtk_liststore_item_derive\" }"},
]
pre-release-hook = [
  "sh",
  "-c",
  "cd .. && git cliff --tag $NEW_VERSION --output CHANGELOG.md"
]
